// This file is automatically generated. Do not modify it manually.

const manifest = JSON.parse(`
{
    "id": "com.ochorocho.nextcloud",
    "name": "Nextcloud Talk",
    "description": "Integrates Nextcloud Talk",
    "version": "0.1.0",
    "min_server_version": "5.12.0",
    "server": {
        "executables": {
            "linux-amd64": "server/dist/plugin-linux-amd64",
            "darwin-amd64": "server/dist/plugin-darwin-amd64",
            "windows-amd64": "server/dist/plugin-windows-amd64.exe"
        },
        "executable": ""
    },
    "webapp": {
        "bundle_path": "webapp/dist/main.js"
    },
    "settings_schema": {
        "header": "Configure Nextcloud instance settings below",
        "footer": "",
        "settings": [
            {
                "key": "NextcloudURL",
                "display_name": "Nextcloud URL",
                "type": "text",
                "help_text": "The URL for a self-hosted Nextcloud server.",
                "placeholder": "https://example.com",
                "default": null
            }
        ]
    }
}
`);

export default manifest;
export const id = manifest.id;
export const version = manifest.version;
